; ═══════════════════════════════════════════════════════════
;  🐾 PET FEEDER — PlatformIO Config
; ═══════════════════════════════════════════════════════════

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino

; Viteză monitor serial
monitor_speed = 115200

; Biblioteci necesare
lib_deps =
    madhephaestus/ESP32Servo@^1.1.1
    bblanchon/ArduinoJson@^7.0.0
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    knolleary/PubSubClient@^2.8
    tzapu/WiFiManager@^2.0.17
